'use client'

import { useState, useCallback, useRef, useEffect } from 'react'
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  Cell,
} from 'recharts'
import {
  calculatePayroll,
  type TaxBracket,
  type SocialSecurityRate,
  type CalculationResult,
} from '@/lib/calculator'
import EmailCapture from '@/components/EmailCapture'

// ─── Types ────────────────────────────────────────────────────────────────────

interface CalculatorProps {
  countryCode: string
  countryName: string
  currencyCode: string
  taxBrackets: TaxBracket[]
  ssRates: SocialSecurityRate[]
  taxYear: number
  onSaveRequest?: (result: CalculationResult, gross: number, period: 'monthly' | 'annual') => void
  isAuthenticated?: boolean
  initialSalary?: string
  initialPeriod?: 'monthly' | 'annual'
  saveStatus?: 'idle' | 'saving' | 'saved' | 'duplicate' | 'error'
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const CURRENCY_SYMBOLS: Record<string, string> = {
  GBP: '£', USD: '$', EUR: '€', JPY: '¥', AUD: 'A$',
  CAD: 'C$', CHF: 'Fr', SEK: 'kr', NOK: 'kr', DKK: 'kr',
  SGD: 'S$', HKD: 'HK$', NZD: 'NZ$', ZAR: 'R', BRL: 'R$',
  INR: '₹', CNY: '¥', KRW: '₩', MXN: '$', AED: 'د.إ',
}

function fmt(amount: number, currency: string): string {
  const symbol = CURRENCY_SYMBOLS[currency] ?? currency + ' '
  return symbol + Math.round(amount).toLocaleString('en-GB')
}

function pct(rate: number): string {
  return rate.toFixed(2) + '%'
}

const CHART_COLORS = {
  net: '#22c55e',
  tax: '#f59e0b',
  employeeSs: '#3b82f6',
  employerSs: '#8b5cf6',
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function Calculator({
  countryCode,
  countryName,
  currencyCode,
  taxBrackets,
  ssRates,
  taxYear,
  onSaveRequest,
  isAuthenticated = false,
  initialSalary,
  initialPeriod,
  saveStatus = 'idle',
}: CalculatorProps) {
  const [gross, setGross] = useState<string>(initialSalary || '')
  const [period, setPeriod] = useState<'monthly' | 'annual'>(initialPeriod || 'annual')
  const [view, setView] = useState<'monthly' | 'annual'>('monthly')
  const [result, setResult] = useState<CalculationResult | null>(null)
  const [copied, setCopied] = useState(false)
  const [hasData] = useState(taxBrackets.length > 0 || ssRates.length > 0)
  const resultsRef = useRef<HTMLDivElement>(null)

  // Auto-run calculation if initial salary provided (from Re-run link)
  useEffect(() => {
    if (initialSalary && parseFloat(initialSalary) > 0) {
      const value = parseFloat(initialSalary)
      const res = calculatePayroll(value, initialPeriod || 'annual', taxBrackets, ssRates, currencyCode, taxYear)
      setResult(res)
    }
  }, [])

  // ── Calculate ──────────────────────────────────────────────────────────────

  const handleCalculate = useCallback(() => {
    const value = parseFloat(gross.replace(/,/g, ''))
    if (!value || value <= 0) return
    const res = calculatePayroll(value, period, taxBrackets, ssRates, currencyCode, taxYear)
    setResult(res)
    setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100)
  }, [gross, period, taxBrackets, ssRates, currencyCode, taxYear])

  // ── Share link ─────────────────────────────────────────────────────────────

  const handleCopyLink = useCallback(() => {
    const url = new URL(window.location.href)
    url.searchParams.set('salary', gross)
    url.searchParams.set('period', period)
    navigator.clipboard.writeText(url.toString()).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }, [gross, period])

  // ── PDF download ───────────────────────────────────────────────────────────

  const handleDownloadPDF = useCallback(async () => {
    if (!result) return
    const { jsPDF } = await import('jspdf')
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
    const currency = result.currency_code
    const v = view

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.text(`Payroll Calculation — ${countryName}`, 20, 20)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(`Tax Year: ${result.tax_year}  |  Currency: ${currency}  |  Generated by HRLake.com`, 20, 28)

    const rows = [
      ['Gross Salary', fmt(v === 'monthly' ? result.gross_monthly : result.gross_annual, currency)],
      ['Income Tax', fmt(v === 'monthly' ? result.income_tax_monthly : result.income_tax_annual, currency)],
      ['Employee Social Security', fmt(v === 'monthly' ? result.employee_ss_monthly : result.employee_ss_annual, currency)],
      ['Net Take-Home Pay', fmt(v === 'monthly' ? result.net_monthly : result.net_annual, currency)],
      ['Employer Social Security', fmt(v === 'monthly' ? result.employer_ss_monthly : result.employer_ss_annual, currency)],
      ['Total Employer Cost', fmt(v === 'monthly' ? result.total_employer_cost_monthly : result.total_employer_cost_annual, currency)],
      ['Effective Tax Rate', pct(result.effective_tax_rate)],
      ['Effective Total Deduction Rate', pct(result.effective_total_deduction_rate)],
    ]

    let y = 40
    doc.setFont('helvetica', 'bold')
    doc.text(v === 'monthly' ? 'Monthly Figures' : 'Annual Figures', 20, y)
    y += 6

    doc.setLineWidth(0.3)
    doc.line(20, y, 190, y)
    y += 4

    for (const [label, value] of rows) {
      doc.setFont('helvetica', 'normal')
      doc.text(label, 20, y)
      doc.setFont('helvetica', 'bold')
      doc.text(value, 190, y, { align: 'right' })
      y += 7
    }

    y += 4
    doc.line(20, y, 190, y)
    y += 8
    doc.setFont('helvetica', 'bold')
    doc.text('Income Tax Breakdown', 20, y)
    y += 6

    for (const b of result.tax_bracket_breakdown) {
      doc.setFont('helvetica', 'normal')
      doc.text(`${b.bracket_name} (${b.rate}%)`, 20, y)
      doc.text(fmt(v === 'monthly' ? b.tax_due / 12 : b.tax_due, currency), 190, y, { align: 'right' })
      y += 6
    }

    y += 4
    doc.setFontSize(8)
    doc.setTextColor(120)
    doc.text('Disclaimer: This calculation is for indicative purposes only. Always consult a qualified payroll professional.', 20, y)

    doc.save(`payroll-${countryCode.toLowerCase()}-${result.tax_year}.pdf`)
  }, [result, view, countryName, countryCode])

  // ── Chart data ─────────────────────────────────────────────────────────────

  const chartData = result
    ? [
        { name: 'Net Pay', value: Math.round(view === 'monthly' ? result.net_monthly : result.net_annual), color: CHART_COLORS.net },
        { name: 'Income Tax', value: Math.round(view === 'monthly' ? result.income_tax_monthly : result.income_tax_annual), color: CHART_COLORS.tax },
        { name: 'Employee SS', value: Math.round(view === 'monthly' ? result.employee_ss_monthly : result.employee_ss_annual), color: CHART_COLORS.employeeSs },
        { name: 'Employer Contribution', value: Math.round(view === 'monthly' ? result.employer_ss_monthly : result.employer_ss_annual), color: CHART_COLORS.employerSs },
      ]
    : []

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div className="space-y-8">

      {/* No data warning */}
      {!hasData && (
        <div className="rounded-lg border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-800">
          <strong>Data coming soon.</strong> Tax bracket and social security data for {countryName} has not yet been populated. The calculator structure is ready — results will appear once data is added in Task 15.
        </div>
      )}

      {/* ── Input panel ── */}
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h2 className="mb-5 text-lg font-semibold text-slate-900">Enter Salary Details</h2>

        <div className="grid gap-5 sm:grid-cols-2">

          {/* Gross salary */}
          <div className="sm:col-span-2">
            <label className="mb-1.5 block text-sm font-medium text-slate-700">
              Gross Salary ({currencyCode})
            </label>
            <input
              type="number"
              value={gross}
              onChange={(e) => setGross(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleCalculate()}
              placeholder="e.g. 60000"
              min={0}
              className="w-full rounded-lg border border-slate-300 bg-white px-4 py-3 text-lg font-semibold text-slate-900 placeholder:font-normal placeholder:text-slate-400 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
            />
          </div>

          {/* Period */}
          <div>
            <label className="mb-1.5 block text-sm font-medium text-slate-700">
              Salary Period
            </label>
            <div className="flex rounded-lg border border-slate-300 overflow-hidden">
              {(['annual', 'monthly'] as const).map((p) => (
                <button
                  key={p}
                  onClick={() => setPeriod(p)}
                  className={`flex-1 py-3 text-sm font-medium transition-colors ${
                    period === p
                      ? 'bg-blue-600 text-white'
                      : 'bg-white text-slate-600 hover:bg-slate-50'
                  }`}
                >
                  {p.charAt(0).toUpperCase() + p.slice(1)}
                </button>
              ))}
            </div>
          </div>

          {/* Currency display */}
          <div>
            <label className="mb-1.5 block text-sm font-medium text-slate-700">
              Currency
            </label>
            <div className="flex h-[46px] items-center rounded-lg border border-slate-200 bg-slate-50 px-4 text-sm text-slate-600">
              {currencyCode} — results shown in local currency
            </div>
          </div>

        </div>

        <button
          onClick={handleCalculate}
          disabled={!gross || parseFloat(gross) <= 0}
          className="mt-6 w-full rounded-xl bg-blue-600 px-6 py-3.5 text-base font-semibold text-white shadow-sm transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-40"
        >
          Calculate Payroll
        </button>
      </div>

      {/* ── Results ── */}
      {result && (
        <div ref={resultsRef} className="space-y-6">

          {/* View toggle + actions */}
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex rounded-lg border border-slate-200 overflow-hidden">
              {(['monthly', 'annual'] as const).map((v) => (
                <button
                  key={v}
                  onClick={() => setView(v)}
                  className={`px-5 py-2 text-sm font-medium transition-colors ${
                    view === v
                      ? 'bg-slate-900 text-white'
                      : 'bg-white text-slate-600 hover:bg-slate-50'
                  }`}
                >
                  {v.charAt(0).toUpperCase() + v.slice(1)}
                </button>
              ))}
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleCopyLink}
                className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3.5 py-2 text-xs font-medium text-slate-500 hover:text-slate-800 hover:border-slate-300 hover:bg-slate-50 transition-all"
              >
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>
                {copied ? 'Copied' : 'Share'}
              </button>
              <button
                onClick={handleDownloadPDF}
                className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3.5 py-2 text-xs font-medium text-slate-500 hover:text-slate-800 hover:border-slate-300 hover:bg-slate-50 transition-all"
              >
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
                Export PDF
              </button>
              {onSaveRequest && (
                <button
                  onClick={() => {
                    if (!isAuthenticated) {
                      window.location.href = '/sign-in?redirect=' + encodeURIComponent(window.location.pathname)
                      return
                    }
                    onSaveRequest(result, parseFloat(gross), period)
                  }}
                  disabled={saveStatus === 'saving'}
                  className="inline-flex items-center gap-1.5 rounded-lg bg-slate-900 hover:bg-slate-700 disabled:opacity-60 disabled:cursor-not-allowed px-3.5 py-2 text-xs font-medium text-white transition-all"
                >
                  {saveStatus === 'saving' ? (
                    <>
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="animate-spin"><path d="M21 12a9 9 0 1 1-6.219-8.56"/></svg>
                      Saving…
                    </>
                  ) : saveStatus === 'saved' ? (
                    <>
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
                      Saved
                    </>
                  ) : (
                    <>
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg>
                      {isAuthenticated ? 'Save Calculation' : 'Sign in to Save'}
                    </>
                  )}
                </button>
              )}
            </div>
          </div>

          {/* Summary table */}
          <div className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden">
            <div className="border-b border-slate-100 px-6 py-4">
              <h3 className="font-semibold text-slate-900">
                {view === 'monthly' ? 'Monthly' : 'Annual'} Breakdown — {result.currency_code} · Tax Year {result.tax_year}
              </h3>
            </div>
            <table className="w-full">
              <tbody className="divide-y divide-slate-100">
                <Row label="Gross Salary" value={fmt(view === 'monthly' ? result.gross_monthly : result.gross_annual, result.currency_code)} bold />
                <Row label="Income Tax" value={`− ${fmt(view === 'monthly' ? result.income_tax_monthly : result.income_tax_annual, result.currency_code)}`} negative />
                <Row label="Employee Social Security" value={`− ${fmt(view === 'monthly' ? result.employee_ss_monthly : result.employee_ss_annual, result.currency_code)}`} negative />
                <Row label="Net Take-Home Pay" value={fmt(view === 'monthly' ? result.net_monthly : result.net_annual, result.currency_code)} highlight />
                <Row label="" value="" divider />
                <Row label="Employer Social Security" value={`+ ${fmt(view === 'monthly' ? result.employer_ss_monthly : result.employer_ss_annual, result.currency_code)}`} muted />
                <Row label="Total Employer Cost" value={fmt(view === 'monthly' ? result.total_employer_cost_monthly : result.total_employer_cost_annual, result.currency_code)} bold />
                <Row label="" value="" divider />
                <Row label="Effective Tax Rate" value={pct(result.effective_tax_rate)} muted />
                <Row label="Effective Total Deduction Rate" value={pct(result.effective_total_deduction_rate)} muted />
              </tbody>
            </table>
          </div>

          {/* Chart */}
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h3 className="mb-4 font-semibold text-slate-900">Visual Breakdown</h3>
            <ResponsiveContainer width="100%" height={220}>
              <BarChart data={chartData} layout="vertical" margin={{ left: 16, right: 24, top: 0, bottom: 0 }}>
                <XAxis
                  type="number"
                  tickFormatter={(v) => fmt(v, result.currency_code)}
                  tick={{ fontSize: 11, fill: '#64748b' }}
                  axisLine={false}
                  tickLine={false}
                />
                <YAxis
                  type="category"
                  dataKey="name"
                  tick={{ fontSize: 12, fill: '#334155' }}
                  axisLine={false}
                  tickLine={false}
                  width={110}
                />
                <Tooltip
                  formatter={(value) => [fmt(Number(value ?? 0), result.currency_code), '']}
                  contentStyle={{ borderRadius: '8px', border: '1px solid #e2e8f0', fontSize: 13 }}
                />
                <Bar dataKey="value" radius={[0, 6, 6, 0]}>
                  {chartData.map((entry, i) => (
                    <Cell key={i} fill={entry.color} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
            <div className="mt-4 flex flex-wrap gap-4">
              {[
                { label: 'Net Pay', color: CHART_COLORS.net },
                { label: 'Income Tax', color: CHART_COLORS.tax },
                { label: 'Employee SS', color: CHART_COLORS.employeeSs },
                { label: 'Employer Contribution', color: CHART_COLORS.employerSs },
              ].map((item) => (
                <div key={item.label} className="flex items-center gap-2">
                  <div className="h-3 w-3 rounded-full" style={{ backgroundColor: item.color }} />
                  <span className="text-xs text-slate-500">{item.label}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Tax bracket breakdown */}
          {result.tax_bracket_breakdown.length > 0 && (
            <div className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden">
              <div className="border-b border-slate-100 px-6 py-4">
                <h3 className="font-semibold text-slate-900">Income Tax — Bracket Detail</h3>
              </div>
              <table className="w-full">
                <thead>
                  <tr className="border-b border-slate-100 bg-slate-50 text-left text-xs font-medium uppercase tracking-wider text-slate-500">
                    <th className="px-6 py-3">Band</th>
                    <th className="px-6 py-3">Rate</th>
                    <th className="px-6 py-3 text-right">Taxable Amount</th>
                    <th className="px-6 py-3 text-right">Tax Due</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {result.tax_bracket_breakdown.map((b, i) => (
                    <tr key={i}>
                      <td className="px-6 py-3 text-sm text-slate-700">{b.bracket_name}</td>
                      <td className="px-6 py-3 text-sm font-medium text-slate-900">{b.rate}%</td>
                      <td className="px-6 py-3 text-right text-sm text-slate-700">
                        {fmt(view === 'monthly' ? b.taxable_amount / 12 : b.taxable_amount, result.currency_code)}
                      </td>
                      <td className="px-6 py-3 text-right text-sm font-semibold text-amber-600">
                        {fmt(view === 'monthly' ? b.tax_due / 12 : b.tax_due, result.currency_code)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* SS breakdown */}
          {(result.employee_ss_breakdown.length > 0 || result.employer_ss_breakdown.length > 0) && (
            <div className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden">
              <div className="border-b border-slate-100 px-6 py-4">
                <h3 className="font-semibold text-slate-900">Social Security — Detail</h3>
              </div>
              <table className="w-full">
                <thead>
                  <tr className="border-b border-slate-100 bg-slate-50 text-left text-xs font-medium uppercase tracking-wider text-slate-500">
                    <th className="px-6 py-3">Contribution</th>
                    <th className="px-6 py-3">Party</th>
                    <th className="px-6 py-3">Rate</th>
                    <th className="px-6 py-3 text-right">Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {result.employee_ss_breakdown.map((s, i) => (
                    <tr key={`emp-${i}`}>
                      <td className="px-6 py-3 text-sm text-slate-700">{s.description}</td>
                      <td className="px-6 py-3 text-sm text-slate-500">Employee</td>
                      <td className="px-6 py-3 text-sm font-medium text-slate-900">{s.rate}%</td>
                      <td className="px-6 py-3 text-right text-sm font-semibold text-blue-600">
                        {fmt(view === 'monthly' ? s.contribution / 12 : s.contribution, result.currency_code)}
                      </td>
                    </tr>
                  ))}
                  {result.employer_ss_breakdown.map((s, i) => (
                    <tr key={`er-${i}`}>
                      <td className="px-6 py-3 text-sm text-slate-700">{s.description}</td>
                      <td className="px-6 py-3 text-sm text-slate-500">Employer</td>
                      <td className="px-6 py-3 text-sm font-medium text-slate-900">{s.rate}%</td>
                      <td className="px-6 py-3 text-right text-sm font-semibold text-purple-600">
                        {fmt(view === 'monthly' ? s.contribution / 12 : s.contribution, result.currency_code)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Email capture — after results */}
          <div className="rounded-2xl border border-blue-100 bg-blue-50 p-6">
            <p className="text-blue-600 text-xs font-bold uppercase tracking-widest mb-1">Stay informed</p>
            <h3 className="font-bold text-slate-900 text-lg mb-1">Stay up to date on global employment costs.</h3>
            <p className="text-slate-500 text-sm mb-4">Monthly HR and payroll updates — rate changes, new country data, and compliance alerts. Free, no spam.</p>
            <EmailCapture
              source="calculator_results"
              variant="compact"
            />
          </div>

          {/* Disclaimer */}
          <p className="text-xs text-slate-400">
            This calculation is for indicative purposes only. Tax rules are complex and vary by individual circumstances.
            Always consult a qualified payroll professional or tax adviser. Data sourced from official government publications — Tax Year {result.tax_year}.
          </p>

        </div>
      )}
    </div>
  )
}

// ─── Helper sub-component ─────────────────────────────────────────────────────

function Row({
  label,
  value,
  bold,
  highlight,
  negative,
  muted,
  divider,
}: {
  label: string
  value: string
  bold?: boolean
  highlight?: boolean
  negative?: boolean
  muted?: boolean
  divider?: boolean
}) {
  if (divider) return <tr><td colSpan={2} className="py-1" /></tr>
  return (
    <tr className={highlight ? 'bg-green-50' : ''}>
      <td className={`px-6 py-3.5 text-sm ${muted ? 'text-slate-500' : 'text-slate-700'} ${bold ? 'font-semibold' : ''} ${highlight ? 'font-bold text-green-800' : ''}`}>
        {label}
      </td>
      <td className={`px-6 py-3.5 text-right text-sm tabular-nums ${negative ? 'text-red-600 font-semibold' : ''} ${bold ? 'font-bold text-slate-900' : ''} ${highlight ? 'font-bold text-green-700' : ''} ${muted ? 'text-slate-500' : ''}`}>
        {value}
      </td>
    </tr>
  )
}
